<?php

namespace App\Services;

use App\Models\Theme;
use Illuminate\Support\Str;

class ThemeGeneratorService
{
    /**
     * Generate both the Livewire component class and the Blade view for a theme.
     */
    public function generate(Theme $theme): void
    {
        $this->generateComponentClass($theme);
        $this->generateBladeView($theme);

        // Update theme's view_file to point to the generated view
        $theme->update(['view_file' => 'themes.' . $theme->slug]);
    }

    /**
     * Generate Livewire component class (follows AdatBone.php pattern).
     */
    public function generateComponentClass(Theme $theme): string
    {
        $className = Str::studly($theme->slug);
        $viewName = 'livewire.themes.' . $theme->slug;
        $filePath = app_path("Livewire/Themes/{$className}.php");

        // Don't overwrite if manually created
        if (file_exists($filePath) && !$this->isGenerated($filePath)) {
            return $filePath;
        }

        $content = <<<PHP
<?php

// AUTO-GENERATED by ThemeGeneratorService — do not edit manually.
// Re-generated when theme sections are updated via Theme Builder.

namespace App\Livewire\Themes;

use App\Models\Invitation;
use Livewire\Attributes\Locked;
use Livewire\Attributes\Validate;
use Livewire\Component;

class {$className} extends Component
{
    #[Locked]
    public Invitation \$invitation;

    #[Locked]
    public ?array \$metadata = null;

    #[Locked]
    public ?string \$guestName = null;

    #[Validate('required|string|min:3|max:255')]
    public string \$rsvpName = '';

    #[Validate('required|string')]
    public string \$rsvpStatus = 'confirmed';

    #[Validate('required|integer|min:1|max:10')]
    public int \$rsvpGuests = 1;

    #[Validate('required|string|min:5|max:1000')]
    public string \$rsvpMessage = '';

    public function mount(Invitation \$invitation, ?array \$metadata = null): void
    {
        \$this->invitation = \$invitation;
        \$this->metadata = \$metadata;
        \$this->guestName = request('kpd', 'Tamu Undangan');
    }

    public function submitRSVP(): void
    {
        \$this->validate();

        \$this->invitation->wishes()->create([
            'name' => \$this->rsvpName,
            'attendance_status' => \$this->rsvpStatus,
            'pax' => \$this->rsvpGuests,
            'message' => \$this->rsvpMessage,
        ]);

        \$this->reset(['rsvpName', 'rsvpStatus', 'rsvpGuests', 'rsvpMessage']);
        session()->flash('message', 'Terima kasih, ucapan dan doa Anda telah tersimpan!');
    }

    public function render()
    {
        return view('{$viewName}');
    }
}
PHP;

        // Ensure directory exists
        $dir = dirname($filePath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($filePath, $content);

        return $filePath;
    }

    /**
     * Generate Blade view that composes section partials (follows adat-bone pattern).
     */
    public function generateBladeView(Theme $theme): string
    {
        $slug = $theme->slug;
        $filePath = resource_path("views/livewire/themes/{$slug}.blade.php");

        $config = $theme->sections_config ?? Theme::defaultSectionsConfig();
        $enabledSections = collect($config['sections'] ?? [])
            ->where('enabled', true)
            ->sortBy('order')
            ->values();

        $frame = $config['frame'] ?? [];
        $nav = $config['nav'] ?? [];

        // Build colors CSS
        $bgColor = $theme->background_color ?? '#5d071f';
        $baseColor = $theme->text_color ?? '#ffffff';
        $accentColor = $theme->accent_color ?? '#d4b051';
        $primaryColor = $theme->primary_color ?? '#d4b051';
        $headingFont = $theme->heading_font ?? 'Fraunces';
        $accentFont = $theme->accent_font ?? 'Great Vibes';
        $bodyFont = $theme->body_font ?? 'Parisienne';
        $menuBg = $nav['bg_color'] ?? 'rgba(118, 19, 50, 0.95)';
        $menuActive = $nav['active_color'] ?? '#d4b051';
        $menuInactive = $nav['inactive_color'] ?? '#ffffff';
        $btnColor = $theme->secondary_color ?? '#3d0d19';

        // Build Google Fonts URL
        $fonts = collect([$headingFont, $accentFont, $bodyFont])
            ->unique()
            ->map(fn($f) => str_replace(' ', '+', $f))
            ->implode('&family=');
        $fontsUrl = "https://fonts.googleapis.com/css2?family={$fonts}&display=swap";

        // Build slide names for Alpine data
        $slideNames = $enabledSections->pluck('id')->toArray();
        $slidesJson = json_encode($slideNames);

        // Build sections includes
        $slideIndex = 0;
        $sectionIncludes = '';
        $coverInclude = '';

        foreach ($enabledSections as $section) {
            $id = $section['id'];
            $sc = json_encode($section['config'] ?? [], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $frameJson = json_encode($frame, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

            if ($id === 'cover') {
                $coverInclude = "    @include('livewire.themes.sections._cover', ['invitation' => \$invitation, 'sc' => json_decode('{$sc}', true), 'frame' => json_decode('{$frameJson}', true)])\n";
            } else {
                $slideIndex++;
                $sectionIncludes .= "        @include('livewire.themes.sections._{$id}', ['invitation' => \$invitation, 'sc' => json_decode('{$sc}', true), 'frame' => json_decode('{$frameJson}', true), 'slideIndex' => {$slideIndex}])\n";
            }
        }

        // Build enabled sections data for nav
        $navSectionsData = [];
        $navSlideIdx = 0;
        foreach ($enabledSections as $section) {
            if ($section['id'] === 'cover') continue;
            $navSlideIdx++;
            $navSectionsData[] = array_merge($section, ['_slideIndex' => $navSlideIdx]);
        }
        $navSectionsJson = json_encode($navSectionsData, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        $navJson = json_encode($nav, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

        $content = <<<BLADE
{{-- AUTO-GENERATED by ThemeGeneratorService — do not edit manually. --}}
{{-- Theme: {$theme->name} (slug: {$slug}) --}}
{{-- Re-generated when theme sections are updated via Theme Builder. --}}

@section('title', 'Wedding of ' . \$invitation->groom_nickname . ' & ' . \$invitation->bride_nickname)

@push('fonts')
<link href="{$fontsUrl}" rel="stylesheet">
@endpush

@push('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
<style>
:root {
    --inv-bg: {$bgColor};
    --inv-base: {$baseColor};
    --inv-accent: {$accentColor};
    --inv-border: {$primaryColor};
    --font-base: '{$headingFont}', serif;
    --font-accent: '{$accentFont}', cursive;
    --font-latin: '{$bodyFont}', cursive;
    --menu-bg: {$menuBg};
    --menu-inactive: {$menuInactive};
    --menu-active: {$menuActive};
    --btn-color: {$btnColor};
}

*, *::before, *::after { box-sizing: border-box; }

body {
    background-color: var(--inv-bg);
    color: var(--inv-base);
    font-family: var(--font-base);
    overflow: hidden;
    -webkit-font-smoothing: antialiased;
}

.animate__slower { animation-duration: 2s; }
.animate__slow { animation-duration: 1.5s; }

.satumomen_track {
    height: 100dvh; width: 100vw;
    overflow-y: auto; overflow-x: hidden;
    scroll-snap-type: y mandatory; scroll-behavior: smooth;
    position: relative; background-color: var(--inv-bg);
    -webkit-overflow-scrolling: touch;
}
.satumomen_slide {
    height: 100dvh; width: 100vw;
    scroll-snap-align: start; position: relative;
    display: flex; justify-content: center; align-items: center;
}
.container-mobile {
    width: 100%; max-width: 480px; height: 100%;
    position: relative; margin: 0 auto;
    background-size: cover; background-position: center;
    background-color: var(--inv-bg); overflow: hidden;
    box-shadow: 0 0 30px rgba(0,0,0,0.6);
}
.frame { position: absolute; inset: 0; pointer-events: none; z-index: 10; }
.frame img { position: absolute; z-index: 10; }
.frame-tl { top: 0; left: 0; max-width: 40%; max-height: 30%; }
.frame-tr { top: 0; right: 0; max-width: 40%; max-height: 30%; }
.frame-bl { bottom: 0; left: 0; max-width: 40%; max-height: 30%; }
.frame-br { bottom: 0; right: 0; max-width: 40%; max-height: 30%; }
.frame-tc { top: 0; left: 50%; transform: translateX(-50%); width: 100%; max-height: 15%; }
.frame-bc { bottom: 0; left: 50%; transform: translateX(-50%); width: 100%; max-height: 15%; }
.frame-lc { left: 0; top: 0; height: 100%; width: auto; max-width: 12%; }
.frame-rc { right: 0; top: 0; height: 100%; width: auto; max-width: 12%; }

.satumomen_nav_wrap {
    position: fixed; bottom: 20px; left: 0; right: 0; z-index: 50;
    display: flex; justify-content: center; pointer-events: none;
}
.satumomen_menu {
    width: 260px; backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    padding: 8px 0; overflow: hidden;
    box-shadow: 0 4px 30px rgba(0,0,0,0.45), inset 0 0 0 1px rgba(212,176,81,0.2);
    border-radius: 50px; pointer-events: auto;
}
.satumomen_menu_inner {
    display: flex; flex-direction: row;
    transition: transform 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}
.satumomen_menu_item {
    color: var(--menu-inactive); text-align: center; font-size: 9px; cursor: pointer;
    transition: color 0.3s, opacity 0.3s;
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    gap: 2px; opacity: 0.45; flex: 0 0 65px; width: 65px; height: 42px;
    white-space: nowrap; position: relative;
}
.satumomen_menu_item.active { color: var(--menu-active); opacity: 1; }
.satumomen_menu_item.active::after {
    content: ''; position: absolute; bottom: 0; left: 50%; transform: translateX(-50%);
    width: 5px; height: 5px; background: var(--inv-accent); border-radius: 50%;
}
.satumomen_menu_item svg { width: 16px; height: 16px; }

.font-accent { font-family: var(--font-accent); }
.font-latin { font-family: var(--font-latin); }
.color-accent { color: var(--inv-accent); }

.form-input {
    width: 100%; padding: 12px 15px; border-radius: 8px;
    background: rgba(255,255,255,0.08); border: 1px solid rgba(212,176,81,0.4);
    color: white; margin-bottom: 12px; font-family: var(--font-base);
    font-size: 14px; transition: border-color 0.3s ease; outline: none;
}
.form-input:focus { border-color: var(--inv-accent); background: rgba(255,255,255,0.12); }
.form-input::placeholder { color: rgba(255,255,255,0.5); }

.btn-primary {
    background-color: var(--btn-color); color: var(--inv-accent);
    border: 1px solid var(--inv-accent); padding: 12px 28px; border-radius: 50px;
    font-family: sans-serif; font-weight: 600; font-size: 13px;
    letter-spacing: 0.5px; cursor: pointer; transition: all 0.3s ease;
    display: inline-block; width: 100%; text-align: center;
}
.btn-primary:hover {
    background-color: var(--inv-accent); color: var(--btn-color);
    box-shadow: 0 4px 15px rgba(212,176,81,0.3);
}

.slide-content {
    position: relative; z-index: 20; width: 100%; height: 100%;
    display: flex; flex-direction: column; padding: 60px 28px; overflow-y: auto;
}
.slide-center { justify-content: center; align-items: center; }

#cover-overlay { position: fixed; inset: 0; z-index: 100; background-color: var(--inv-bg); }

.photo-frame {
    width: 120px; height: 120px; margin: 0 auto;
    border: 2px solid var(--inv-accent); border-radius: 50%; overflow: hidden;
    box-shadow: 0 4px 20px rgba(212,176,81,0.2);
}
.photo-frame img { width: 100%; height: 100%; object-fit: cover; }
a { color: inherit; text-decoration: none; }

.satumomen_track::-webkit-scrollbar { display: none; }
.satumomen_track { -ms-overflow-style: none; scrollbar-width: none; }
.slide-content::-webkit-scrollbar { display: none; }
.slide-content { -ms-overflow-style: none; scrollbar-width: none; }
</style>
@endpush

<div style="background-color: var(--inv-bg); height: 100dvh;" x-data="{
    opened: false,
    activeSlide: 0,
    playing: false,
    audioEl: null,
    slides: {$slidesJson},
    init() { this.setupIntersectionObserver(); },
    open() {
        this.opened = true;
        this.\$nextTick(() => {
            this.audioEl = document.getElementById('bgMusic');
            if(this.audioEl) { this.audioEl.play().then(() => this.playing = true).catch(() => {}); }
            this.scrollToSlide(1);
        });
    },
    toggleAudio() {
        if(!this.audioEl) this.audioEl = document.getElementById('bgMusic');
        if(!this.audioEl) return;
        if(this.playing) { this.audioEl.pause(); this.playing = false; }
        else { this.audioEl.play().then(()=>this.playing=true).catch(()=>{}); }
    },
    scrollToSlide(index) {
        if(index < 0 || index >= this.slides.length) return;
        const target = document.getElementById('slide-' + index);
        if(target) { target.scrollIntoView({ behavior: 'smooth' }); this.activeSlide = index; }
    },
    setupIntersectionObserver() {
        let observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if(entry.isIntersecting) {
                    this.activeSlide = parseInt(entry.target.dataset.index);
                    const animatedEls = entry.target.querySelectorAll('.animate__animated');
                    animatedEls.forEach(el => { el.style.animation = 'none'; el.offsetHeight; el.style.animation = null; });
                }
            });
        }, { threshold: 0.5 });
        document.querySelectorAll('.satumomen_slide').forEach((slide) => { observer.observe(slide); });
    }
}">

    @if(\$invitation->music_url)
    <audio id="bgMusic" loop>
        <source src="{{ img_url(\$invitation->music_url) }}" type="audio/mpeg">
    </audio>
    @endif

{$coverInclude}
    {{-- MAIN SLIDER --}}
    <div class="satumomen_track">
{$sectionIncludes}
    </div>

    {{-- BOTTOM NAV MENU --}}
    @include('livewire.themes.sections._nav', [
        'enabledSections' => json_decode('{$navSectionsJson}', true),
        'nav' => json_decode('{$navJson}', true),
        'invitation' => \$invitation,
    ])

</div>
BLADE;

        // Ensure directory exists
        $dir = dirname($filePath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($filePath, $content);

        return $filePath;
    }

    /**
     * Re-generate Blade view (e.g., after sections config update).
     */
    public function regenerateBladeView(Theme $theme): void
    {
        $this->generateBladeView($theme);
    }

    /**
     * Delete generated theme files.
     */
    public function deleteThemeFiles(Theme $theme): void
    {
        $className = Str::studly($theme->slug);
        $phpPath = app_path("Livewire/Themes/{$className}.php");
        $bladePath = resource_path("views/livewire/themes/{$theme->slug}.blade.php");

        if (file_exists($phpPath) && $this->isGenerated($phpPath)) {
            unlink($phpPath);
        }

        if (file_exists($bladePath) && $this->isGenerated($bladePath)) {
            unlink($bladePath);
        }
    }

    /**
     * Check if a file was auto-generated (has our marker comment).
     */
    private function isGenerated(string $filePath): bool
    {
        $content = file_get_contents($filePath);

        return str_contains($content, 'AUTO-GENERATED by ThemeGeneratorService');
    }

    /**
     * Get list of section IDs and their display names.
     */
    public static function getSectionDefinitions(): array
    {
        return [
            'cover' => ['label' => 'Cover', 'icon' => '🏠', 'description' => 'Halaman pembuka dengan tombol "Buka Undangan"'],
            'opening' => ['label' => 'Opening', 'icon' => '💒', 'description' => 'Slide pembuka dengan nama pasangan dan tanggal'],
            'couple' => ['label' => 'Mempelai', 'icon' => '👫', 'description' => 'Profil mempelai pria & wanita dengan foto'],
            'quote' => ['label' => 'Kutipan', 'icon' => '📖', 'description' => 'Ayat suci atau kutipan inspirasional'],
            'lovestory' => ['label' => 'Love Story', 'icon' => '❤️', 'description' => 'Timeline cerita cinta pasangan'],
            'events' => ['label' => 'Acara', 'icon' => '📅', 'description' => 'Detail akad nikah dan resepsi'],
            'maps' => ['label' => 'Lokasi', 'icon' => '📍', 'description' => 'Peta lokasi dengan embed Google Maps'],
            'gallery' => ['label' => 'Galeri', 'icon' => '🖼️', 'description' => 'Galeri foto prewedding'],
            'gift' => ['label' => 'Hadiah', 'icon' => '🎁', 'description' => 'Amplop digital / rekening bank'],
            'rsvp' => ['label' => 'RSVP', 'icon' => '💬', 'description' => 'Konfirmasi kehadiran, countdown, dan ucapan'],
            'closing' => ['label' => 'Penutup', 'icon' => '🙏', 'description' => 'Ucapan terima kasih dan watermark'],
        ];
    }
}
