{{-- AUTO-GENERATED by ThemeGeneratorService — do not edit manually. --}}
{{-- Theme: hantam lurus (slug: hantam-lurus) --}}
{{-- Re-generated when theme sections are updated via Theme Builder. --}}

@section('title', 'Wedding of ' . $invitation->groom_nickname . ' & ' . $invitation->bride_nickname)

@push('fonts')
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Great+Vibes&family=Inter&display=swap" rel="stylesheet">
@endpush

@push('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
<style>
:root {
    --inv-bg: #5d071f;
    --inv-base: #ffffff;
    --inv-accent: #d4b051;
    --inv-border: #5d071f;
    --font-base: 'Playfair Display', serif;
    --font-accent: 'Great Vibes', cursive;
    --font-latin: 'Inter', cursive;
    --menu-bg: rgba(118, 19, 50, 0.95);
    --menu-inactive: #ffffff;
    --menu-active: #d4b051;
    --btn-color: #3d0d19;
}

*, *::before, *::after { box-sizing: border-box; }

body {
    background-color: var(--inv-bg);
    color: var(--inv-base);
    font-family: var(--font-base);
    overflow: hidden;
    -webkit-font-smoothing: antialiased;
}

.animate__slower { animation-duration: 2s; }
.animate__slow { animation-duration: 1.5s; }

.satumomen_track {
    height: 100dvh; width: 100vw;
    overflow-y: auto; overflow-x: hidden;
    scroll-snap-type: y mandatory; scroll-behavior: smooth;
    position: relative; background-color: var(--inv-bg);
    -webkit-overflow-scrolling: touch;
}
.satumomen_slide {
    height: 100dvh; width: 100vw;
    scroll-snap-align: start; position: relative;
    display: flex; justify-content: center; align-items: center;
}
.container-mobile {
    width: 100%; max-width: 480px; height: 100%;
    position: relative; margin: 0 auto;
    background-size: cover; background-position: center;
    background-color: var(--inv-bg); overflow: hidden;
    box-shadow: 0 0 30px rgba(0,0,0,0.6);
}
.frame { position: absolute; inset: 0; pointer-events: none; z-index: 10; }
.frame img { position: absolute; z-index: 10; }
.frame-tl { top: 0; left: 0; max-width: 40%; max-height: 30%; }
.frame-tr { top: 0; right: 0; max-width: 40%; max-height: 30%; }
.frame-bl { bottom: 0; left: 0; max-width: 40%; max-height: 30%; }
.frame-br { bottom: 0; right: 0; max-width: 40%; max-height: 30%; }
.frame-tc { top: 0; left: 50%; transform: translateX(-50%); width: 100%; max-height: 15%; }
.frame-bc { bottom: 0; left: 50%; transform: translateX(-50%); width: 100%; max-height: 15%; }
.frame-lc { left: 0; top: 0; height: 100%; width: auto; max-width: 12%; }
.frame-rc { right: 0; top: 0; height: 100%; width: auto; max-width: 12%; }

.satumomen_nav_wrap {
    position: fixed; bottom: 20px; left: 0; right: 0; z-index: 50;
    display: flex; justify-content: center; pointer-events: none;
}
.satumomen_menu {
    width: 260px; backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    padding: 8px 0; overflow: hidden;
    box-shadow: 0 4px 30px rgba(0,0,0,0.45), inset 0 0 0 1px rgba(212,176,81,0.2);
    border-radius: 50px; pointer-events: auto;
}
.satumomen_menu_inner {
    display: flex; flex-direction: row;
    transition: transform 0.35s cubic-bezier(0.4, 0, 0.2, 1);
}
.satumomen_menu_item {
    color: var(--menu-inactive); text-align: center; font-size: 9px; cursor: pointer;
    transition: color 0.3s, opacity 0.3s;
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    gap: 2px; opacity: 0.45; flex: 0 0 65px; width: 65px; height: 42px;
    white-space: nowrap; position: relative;
}
.satumomen_menu_item.active { color: var(--menu-active); opacity: 1; }
.satumomen_menu_item.active::after {
    content: ''; position: absolute; bottom: 0; left: 50%; transform: translateX(-50%);
    width: 5px; height: 5px; background: var(--inv-accent); border-radius: 50%;
}
.satumomen_menu_item svg { width: 16px; height: 16px; }

.font-accent { font-family: var(--font-accent); }
.font-latin { font-family: var(--font-latin); }
.color-accent { color: var(--inv-accent); }

.form-input {
    width: 100%; padding: 12px 15px; border-radius: 8px;
    background: rgba(255,255,255,0.08); border: 1px solid rgba(212,176,81,0.4);
    color: white; margin-bottom: 12px; font-family: var(--font-base);
    font-size: 14px; transition: border-color 0.3s ease; outline: none;
}
.form-input:focus { border-color: var(--inv-accent); background: rgba(255,255,255,0.12); }
.form-input::placeholder { color: rgba(255,255,255,0.5); }

.btn-primary {
    background-color: var(--btn-color); color: var(--inv-accent);
    border: 1px solid var(--inv-accent); padding: 12px 28px; border-radius: 50px;
    font-family: sans-serif; font-weight: 600; font-size: 13px;
    letter-spacing: 0.5px; cursor: pointer; transition: all 0.3s ease;
    display: inline-block; width: 100%; text-align: center;
}
.btn-primary:hover {
    background-color: var(--inv-accent); color: var(--btn-color);
    box-shadow: 0 4px 15px rgba(212,176,81,0.3);
}

.slide-content {
    position: relative; z-index: 20; width: 100%; height: 100%;
    display: flex; flex-direction: column; padding: 60px 28px; overflow-y: auto;
}
.slide-center { justify-content: center; align-items: center; }

#cover-overlay { position: fixed; inset: 0; z-index: 100; background-color: var(--inv-bg); }

.photo-frame {
    width: 120px; height: 120px; margin: 0 auto;
    border: 2px solid var(--inv-accent); border-radius: 50%; overflow: hidden;
    box-shadow: 0 4px 20px rgba(212,176,81,0.2);
}
.photo-frame img { width: 100%; height: 100%; object-fit: cover; }
a { color: inherit; text-decoration: none; }

.satumomen_track::-webkit-scrollbar { display: none; }
.satumomen_track { -ms-overflow-style: none; scrollbar-width: none; }
.slide-content::-webkit-scrollbar { display: none; }
.slide-content { -ms-overflow-style: none; scrollbar-width: none; }
</style>
@endpush

<div style="background-color: var(--inv-bg); height: 100dvh;" x-data="{
    opened: false,
    activeSlide: 0,
    playing: false,
    audioEl: null,
    slides: ["cover","opening","couple","quote","lovestory","events","maps","gallery","gift","rsvp","closing"],
    init() { this.setupIntersectionObserver(); },
    open() {
        this.opened = true;
        this.$nextTick(() => {
            this.audioEl = document.getElementById('bgMusic');
            if(this.audioEl) { this.audioEl.play().then(() => this.playing = true).catch(() => {}); }
            this.scrollToSlide(1);
        });
    },
    toggleAudio() {
        if(!this.audioEl) this.audioEl = document.getElementById('bgMusic');
        if(!this.audioEl) return;
        if(this.playing) { this.audioEl.pause(); this.playing = false; }
        else { this.audioEl.play().then(()=>this.playing=true).catch(()=>{}); }
    },
    scrollToSlide(index) {
        if(index < 0 || index >= this.slides.length) return;
        const target = document.getElementById('slide-' + index);
        if(target) { target.scrollIntoView({ behavior: 'smooth' }); this.activeSlide = index; }
    },
    setupIntersectionObserver() {
        let observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if(entry.isIntersecting) {
                    this.activeSlide = parseInt(entry.target.dataset.index);
                    const animatedEls = entry.target.querySelectorAll('.animate__animated');
                    animatedEls.forEach(el => { el.style.animation = 'none'; el.offsetHeight; el.style.animation = null; });
                }
            });
        }, { threshold: 0.5 });
        document.querySelectorAll('.satumomen_slide').forEach((slide) => { observer.observe(slide); });
    }
}">

    @if($invitation->music_url)
    <audio id="bgMusic" loop>
        <source src="{{ img_url($invitation->music_url) }}" type="audio/mpeg">
    </audio>
    @endif

    @include('livewire.themes.sections._cover', ['invitation' => $invitation, 'sc' => json_decode('{"title_text":"The Wedding Of","button_text":"Buka Undangan","overlay_gradient":"linear-gradient(to bottom, rgba(93,7,31,0.75) 0%, rgba(93,7,31,0.45) 35%, rgba(93,7,31,0.35) 55%, rgba(93,7,31,0.92) 85%, rgba(93,7,31,0.98) 100%)"}', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true)])

    {{-- MAIN SLIDER --}}
    <div class="satumomen_track">
        @include('livewire.themes.sections._opening', ['invitation' => $invitation, 'sc' => json_decode('{"overlay_gradient":"linear-gradient(to bottom, rgba(93,7,31,0.6), rgba(93,7,31,0.9))"}', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 1])
        @include('livewire.themes.sections._couple', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 2])
        @include('livewire.themes.sections._quote', ['invitation' => $invitation, 'sc' => json_decode('{"quote_text":"Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.","quote_title":"QS. Ar-Rum 21"}', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 3])
        @include('livewire.themes.sections._lovestory', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 4])
        @include('livewire.themes.sections._events', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 5])
        @include('livewire.themes.sections._maps', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 6])
        @include('livewire.themes.sections._gallery', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 7])
        @include('livewire.themes.sections._gift', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 8])
        @include('livewire.themes.sections._rsvp', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 9])
        @include('livewire.themes.sections._closing', ['invitation' => $invitation, 'sc' => json_decode('[]', true), 'frame' => json_decode('{"bl":"/assets/themes/adat-bone/bl.webp","br":"/assets/themes/adat-bone/br.webp","tl":"/assets/themes/adat-bone/tl.webp","tr":"/assets/themes/adat-bone/tr.webp","left":"/assets/themes/adat-bone/left.webp","right":"/assets/themes/adat-bone/right.webp"}', true), 'slideIndex' => 10])

    </div>

    {{-- BOTTOM NAV MENU --}}
    @include('livewire.themes.sections._nav', [
        'enabledSections' => json_decode('[{"id":"opening","order":1,"config":{"overlay_gradient":"linear-gradient(to bottom, rgba(93,7,31,0.6), rgba(93,7,31,0.9))"},"enabled":true,"_slideIndex":1},{"id":"couple","order":2,"config":[],"enabled":true,"_slideIndex":2},{"id":"quote","order":3,"config":{"quote_text":"Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.","quote_title":"QS. Ar-Rum 21"},"enabled":true,"_slideIndex":3},{"id":"lovestory","order":4,"config":[],"enabled":true,"_slideIndex":4},{"id":"events","order":5,"config":[],"enabled":true,"_slideIndex":5},{"id":"maps","order":6,"config":[],"enabled":true,"_slideIndex":6},{"id":"gallery","order":7,"config":[],"enabled":true,"_slideIndex":7},{"id":"gift","order":8,"config":[],"enabled":true,"_slideIndex":8},{"id":"rsvp","order":9,"config":[],"enabled":true,"_slideIndex":9},{"id":"closing","order":10,"config":[],"enabled":true,"_slideIndex":10}]', true),
        'nav' => json_decode('{"bg_color":"rgba(118, 19, 50, 0.95)","active_color":"#d4b051","inactive_color":"#ffffff"}', true),
        'invitation' => $invitation,
    ])

</div>