[program:exoinvite-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/u939198444/domains/exoinvite.site/artisan queue:work database --sleep=3 --tries=2 --timeout=180 --max-jobs=100 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/home/u939198444/domains/exoinvite.site/storage/logs/worker.log
stopwaitsecs=3600
